const DATABASE_NAME = process.env.DATABASE_NAME;
const DATABASE_USER = process.env.DATABASE_USER;
const DATABASE_PASSWORD = process.env.DATABASE_PASSWORD;

export {
  DATABASE_NAME,
  DATABASE_USER,
  DATABASE_PASSWORD,
};
